#

In [1]:
from parser import Parser
from demoparser2 import DemoParser

In [18]:
parser: DemoParser = DemoParser("./Heroric_Dust2_demos/drgn-vs-ursa-m3-dust2.dem")
parser_attributes = ["total_rounds_played", "round"]
bomb_defused = parser.parse_event(
    "bomb_exploded", other=parser_attributes
)
bomb_planted = parser.parse_event(
    "bomb_planted", other=parser_attributes
)

In [19]:
bomb_planted

    site    tick  total_rounds_played  user_name       user_steamid
0    956   13702                    0    abiraju  76561199082242873
1    956   20095                    1      Muk0s  76561199074345785
2    956   27444                    2    tommy10  76561198101515348
3    956   31973                    3      Muk0s  76561199074345785
4    866   53795                    6      Muk0s  76561199074345785
5    866   91354                   11      Muk0s  76561199074345785
6    866  108487                   12  Salazar_9  76561198420829570
7    866  176955                   18  Salazar_9  76561198420829570
8    866  193868                   19      Alv68  76561198036066702
9    866  211385                   21       4X1s  76561198069567550
10   956  223330                   22      Alv68  76561198036066702
11   866  234493                   23      Alv68  76561198036066702
12   956  259490                   26     deeN--  76561198338914091

In [27]:
parser.parse_event('round_end')

           reason  round    tick winner
0            None      1       0   None
1       ct_killed      2    2438      T
2    bomb_defused      3   15198     CT
3   bomb_exploded      4   22719      T
4       ct_killed      5   27627      T
5       ct_killed      6   33408      T
6        t_killed      7   37484     CT
7        t_killed      8   45563     CT
8    bomb_defused      9   55434     CT
9    time_ran_out     10   64522     CT
10       t_killed     11   75896     CT
11       t_killed     12   82405     CT
12      ct_killed     13   91290      T
13       t_killed     14  102354     CT
14   bomb_defused     15  110108     CT
15       t_killed     16  123572     CT
16       t_killed     17  127457     CT
17       t_killed     18  159528     CT
18       t_killed     19  164372     CT
19       t_killed     20  169498     CT
20   bomb_defused     21  178794     CT
21      ct_killed     22  194874      T
22   time_ran_out     23  207042     CT
23  bomb_exploded     24  214009      T
24  bomb_exploded     25  225954      T
25      ct_killed     26  235548      T
26      ct_killed     27  243351      T
27      ct_killed     28  259425      T
28       t_killed     29  267842     CT
29       t_killed     30  276843     CT
30       t_killed     31  285188     CT

In [12]:
parser.parse_ticks(['tick', 'round_end'], ticks=range(10))

    tick            steamid      name
0      1  76561198013295375     bodyy
1      1  76561198179538505   Graviti
2      1  76561198104626893       LNZ
3      1  76561198161056567      nilo
4      1  76561198168198200  Ex3rcice
..   ...                ...       ...
85     9  76561198031890115     Lucky
86     9  76561199137143905  yxngstxr
87     9  76561199079856901   Alkaren
88     9  76561198045739761      Maka
89     9  76561198178209109    xfl0ud

[90 rows x 3 columns]

In [11]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [21]:
events_death  = parser.parse_event('player_death', other=['total_rounds_played'])

In [22]:
events_death[events_death['total_rounds_played'] == 1]

,assistedflash,assister_name,assister_steamid,attacker_name,attacker_steamid,attackerblind,attackerinair,distance,dmg_armor,dmg_health,...,thrusmoke,tick,total_rounds_played,user_name,user_steamid,weapon,weapon_fauxitemid,weapon_itemid,weapon_originalowner_xuid,wipe
7,False,abiraju,76561199082242873,Alv68,76561198036066702,False,False,1.428964,5,61,...,False,2579,1,4X1s,76561198069567550,knife_karambit,17293822569109127675,47679211829,,0
36,False,None,None,Salazar_9,76561198420829570,False,False,3.610277,19,59,...,False,19254,1,pavlysha666,76561198096785767,mp9,17293822569102704674,0,,0
37,False,Salazar_9,76561198420829570,deeN--,76561198338914091,False,False,4.928759,4,20,...,True,19343,1,-whisper666,76561198957049211,famas,17293822569174269962,32427971033,,0
38,False,pavlysha666,76561198096785767,Muk0s,76561199074345785,False,False,4.656774,1,27,...,False,19390,1,Salazar_9,76561198420829570,tec9,17293822569118957598,46425035201,,0
39,False,-whisper666,76561198957049211,abiraju,76561199082242873,False,False,17.680508,3,22,...,True,19395,1,deeN--,76561198338914091,galilar,17293822569134030861,41458010376,,0
40,False,abiraju,76561199082242873,Muk0s,76561199074345785,False,False,17.986315,4,86,...,False,19493,1,4X1s,76561198069567550,tec9,17293822569118957598,46425035201,,0
41,False,None,None,None,None,False,False,0.000000,62,62,...,False,22719,1,Muk0s,76561199074345785,planted_c4,,,,0

In [23]:
start = 20095
end = 22719
events_death[
            (events_death["tick"] >= start) & (events_death["tick"] <= end)
        ]

,assistedflash,assister_name,assister_steamid,attacker_name,attacker_steamid,attackerblind,attackerinair,distance,dmg_armor,dmg_health,...,thrusmoke,tick,total_rounds_played,user_name,user_steamid,weapon,weapon_fauxitemid,weapon_itemid,weapon_originalowner_xuid,wipe
41,False,None,None,None,None,False,False,0.0,62,62,...,False,22719,1,Muk0s,76561199074345785,planted_c4,,,,0

In [16]:
round = bomb_defused['total_rounds_played'].iloc[0]
end_t = bomb_defused[bomb_defused['total_rounds_played'] == round].iloc[0]['tick']
start_t = bomb_planted[bomb_planted['total_rounds_played'] == round].iloc[0]['tick']

In [24]:
ATTRIBUTES = ["team_name", "is_alive"]
TRACE_ATTRIBUTES = ["last_place_name", "tick"]

df = parser.parse_ticks(
    ATTRIBUTES + TRACE_ATTRIBUTES,
    ticks=range(int(start_t), int(end_t + 1)),
)
df

      last_place_name  team_name  is_alive   tick            steamid      name
0              UnderA         CT     False  46152  76561198013295375     bodyy
1              Middle         CT      True  46152  76561198179538505   Graviti
2               ARamp  TERRORIST     False  46152  76561198104626893       LNZ
3           BombsiteA  TERRORIST      True  46152  76561198161056567      nilo
4           BombsiteA         CT     False  46152  76561198168198200  Ex3rcice
...               ...        ...       ...    ...                ...       ...
21285       BombsiteA         CT      True  48280  76561198031890115     Lucky
21286           ARamp  TERRORIST     False  48280  76561199137143905  yxngstxr
21287           LongA  TERRORIST     False  48280  76561199079856901   Alkaren
21288           LongA         CT     False  48280  76561198045739761      Maka
21289           ARamp  TERRORIST     False  48280  76561198178209109    xfl0ud

[21290 rows x 6 columns]